### ISSUE TITLE
block=False is not supported in Linux

### ISSUE THREAD

**Issue by 0n1cOn3** [CalvinLoke/bad-apple#2]
block=False is not supported in Linux, you may need to add an thread to execute playsound():

import threading
...

threading.Thread(target=playsound, args=("tng_bad-apple.mp3",)).start()

**Comment by CalvinLoke** [comment]
Hey there, wasn't aware of the issue thanks. Though when using threading I ran into synchronization issues, so not really too sure on how to rectify that. Will look into it though.

**Comment by dumb-stuff** [comment]
@CalvinLoke you should use the ffmpeg though or just let it record and sent it as video file

**Comment by CalvinLoke** [comment]
Alright, fixed the issue with v3 by replacing the playsound library with pygame. Tested it, and it was able to run on Linux. Thanks for bringing the issue up! @0n1cOn3

**Comment by 0n1cOn3** [comment]
Your welcome.
