### ISSUE TITLE
ModuleNotFOundError: No module named 'PIL'

### ISSUE THREAD

**Issue by ABongoCat** [CalvinLoke/bad-apple#7]
I never used Python but I really wanted to try this. I followed all the steps.

\Desktop\bad-apple-master\touhou_bad_apple_v3.py", line 7, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

**Comment by SuperKaninchen** [comment]
Please make sure that you successfully installed Pillow. Note: If pip says "no such file or directory: 'requirements.txt', it does not mean that all the requirements are satisfied, but that pip could not locate the requirements file!
