### ISSUE TITLE
[touhou_bad_apple_v4.5.py] pygame.error: Unrecognized audio format

### ISSUE THREAD

**Issue by 0n1cOn3** [CalvinLoke/bad-apple#9]
Hey :) Its been a while since my last ticket :) 
I have a new one for yaa. Even when this project was a weekend project. im still amazed about your progress..

It seems to be that there is something wrong with the audio format...

see log:

python3 touhou_bad_apple_v4.5.py 
==============================================================
Select option: 
1) Play
2) Exit
==============================================================
Your option: 1
Please enter the video file name (file must be in root!): BadApple.mp4
MoviePy - Writing audio in audio.mp3
MoviePy - Done.                                                                                                                                                                                    
Beginning ASCII generation...
Progress: [#######################  ] 99% Frame 6570 of 6571 framesASCII generation completed! ASCII generation time: 28.546977519989014Traceback (most recent call last):
  File "touhou_bad_apple_v4.5.py", line 181, in <module>
    main()
  File "touhou_bad_apple_v4.5.py", line 170, in main
    play_audio('audio.mp3')
  File "touhou_bad_apple_v4.5.py", line 24, in play_audio
    pygame.mixer.music.load(path)
pygame.error: Unrecognized audio format

**Comment by CalvinLoke** [comment]
Hi there, are you running it specifically for the purpose of Bad Apple or just for a generic video? Also, it would be great if you could tell me what environment you are running this on.

**Comment by 0n1cOn3** [comment]
Specific for the Bad Apple video purpose.
OS: Ubuntu 20.04 
Shell: zsh/bash
Python: 3.8.10
pip: 20.0.2

**Comment by CalvinLoke** [comment]
No I don't think that is really the issue, though I have to admit when it comes to naming conventions I am terribly garbage at this. Though, if you wish just to play for Bad Apple, I would recommend that you try v4.0 instead, as it would use a pre-existing audio file instead of extracting it from the .mp4 file.

Not too sure why, but there seems to be some error when it comes to generating the audio file in Linux environments. Might be the `moviepy.editor` library requiring some dependencies that Linux lacks. Though I would see if I could resolve the issue on my end.

**Comment by rudy3333** [comment]
Pygame.mixer will not load .MP3 files, because of licensing restrictions. You need to convert them to `.wav` or `.ogg`.
Try [this](https://mp3cutterpro.com/en1/convert-mp3-to-wav) online tool.

**Comment by 0n1cOn3** [comment]
Everything is working as now. 
It has just at the end a small side effect:

When the video ends, Python spits an error

As [mentioned](https://github.com/CalvinLoke/bad-apple/issues/10) here

**Comment by rudy3333** [comment]
I'm pretty sure that's normal, because of automatically generated array.

**Comment by 0n1cOn3** [comment]
> I'm pretty sure that's normal, because of automatically generated array. 

Can this be avoided?
